backend:
  name: git-gateway
  branch: main # Branch to update (master or main)

media_folder: "assets/images" # Where images are saved in the repo
public_folder: "/assets/images" # Where images are found on the live site

collections:
  - name: "releases"
    label: "Release logs"
    folder: "_posts" # Jekyll uses _posts to generate the blog/log
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title (Version Number)", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "text", hint: "1-2 sentences about this update."}
      - {label: "Release Notes Body", name: "body", widget: "markdown", hint: "Use headers like ### Added, ### Fixed, etc."}
